trigger:
- main  # or any other branch you want to sync

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  clean: true

- script: |
    echo "Setting up Git configurations"
    git config --global user.email "venkatareddygirish@gmail.com"
    git config --global user.name "GirishCodeAlchemy"

    echo "Cloning the GitHub repository"
    git clone https://github.com/GirishCodeAlchemy/alchemy-azure-devops.git

    cd alchemy-azure-devops

    echo "Adding Azure DevOps repository as a remote"
    git remote add azure https://$(AZURE_DEVOPS_PAT)@dev.azure.com/girishcodealchemy/alchemy-azure-devops/_git/alchemy-azure-devops

    echo "Pushing changes to Azure DevOps repository"
    git push azure main

  displayName: 'Sync GitHub to Azure DevOps'
  env:
    AZURE_DEVOPS_PAT: $(AZURE_DEVOPS_PAT)
