# azure-pipelines.yml
trigger:
  branches:
    include:
      - main  # or your branch

# Define parameters
parameters:
  - name: environment
    displayName: Environment
    type: string
    default: dev
    values:
      - dev
      - staging
      - prod

  - name: buildType
    displayName: Build Type
    type: string
    default: Debug
    values:
      - Debug
      - Release

  - name: tfVersion
    displayName: Tf Version
    type: string
    default: 1.5.5
    values:
      - 1.5.5
      - 1.5.6

  - name: GCPBackendBucketName
    displayName: GCP Backend Bucket Name
    type: string
    default: test
    values:
      - test
      - dev

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: Build
        displayName: Build Job
        steps:
          - script: echo "Building in $(parameters.environment) environment with $(parameters.buildType) build type."
            displayName: 'Print parameters'

  - stage: Deploy
    displayName: Deploy Stage
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: Deploy Job
        steps:
          - script: echo "Deploying to $(parameters.environment) environment."
            displayName: 'Deploy to environment'
